name = "scruffy"
version = "1.0.0"
description = "A Gleam client for the Scryfall Magic: The Gathering API"
licences = ["MIT"]
repository = { type = "github", user = "nolanwelch", repo = "scruffy" }

# For a full reference of all the available options, you can have a look at
# https://gleam.run/writing-gleam/gleam-toml/.

[dependencies]
gleam_http = ">= 4.0.0 and < 5.0.0"
gleam_json = ">= 3.0.0 and < 4.0.0"
gleam_stdlib = ">= 1.0.0 and < 2.0.0"
glon = ">= 1.0.0 and < 2.0.0"

[dev_dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
